CREATE USER terminal_website WITH PASSWORD 'terminal_website_password';
CREATE USER terminal_website_dev WITH PASSWORD 'terminal_website_dev_password';
CREATE DATABASE terminal_website;
\connect terminal_website;
CREATE SCHEMA prod;
CREATE SCHEMA dev;
REVOKE CONNECT ON DATABASE terminal_website FROM PUBLIC;
GRANT CONNECT ON DATABASE terminal_website TO terminal_website;
GRANT CONNECT ON DATABASE terminal_website TO terminal_website_dev;
GRANT USAGE ON SCHEMA prod TO terminal_website;
GRANT USAGE ON SCHEMA dev TO terminal_website_dev;
ALTER SCHEMA prod OWNER TO terminal_website;
ALTER SCHEMA dev OWNER TO terminal_website_dev;
ALTER USER terminal_website SET search_path TO prod;
ALTER USER terminal_website_dev SET search_path TO dev;
GRANT ALL ON ALL TABLES IN SCHEMA prod TO terminal_website;
GRANT ALL ON ALL TABLES IN SCHEMA dev TO terminal_website_dev;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA prod TO terminal_website;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA dev TO terminal_website_dev;
