name: Test

on:
  push:
    paths:
      - '!**.md'
      - '!.github/**'
      - 'src/**'
      - 'eslint.config.ts'
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:
    inputs:
      autofix:
        description: 'Autofix by ESLint'
        required: false
        type: boolean
        default: false

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Cache dependencies & build
        uses: actions/cache@v5
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
            .next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libpq-dev python3 g++ make
          sudo npm install -g pnpm
          pnpm install
          pnpm run next:typegen
      - name: Run ESLint
        if: ${{ !inputs.autofix }}
        run: pnpm run lint
        env:
          CI: true
          NODE_ENV: development
      - name: Run ESLint (autofix)
        id: eslint_autofix
        if: ${{ inputs.autofix }}
        run: pnpm run lint:fix
        continue-on-error: true
        env:
          CI: true
          NODE_ENV: development
      - name: Push to GitHub
        if: ${{ inputs.autofix }}
        uses: EndBug/add-and-commit@v10.0.0
        with:
          author_name: 'github-actions[bot]'
          author_email: 'action@github.com'
          message: |
            :art: Autofix by ESLint

            Co-authored-by: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      - name: Post Run ESLint (autofix)
        if: ${{ steps.eslint_autofix.outcome == 'failure' }}
        run: exit 1
